apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "benfords-law-api.name" . }}-configmap
data:
  HTTP_PORT: {{ .Values.httpPort | quote }}
  RAPID_API_HOST: {{ .Values.rapidApiHost | quote }}
  RAPID_API_KEY: {{ .Values.rapidApiKey | quote }}
  # todo: move to secrets
